name: Build

on:
  workflow_call:
    inputs:
      git-tag:
        type: string
        required: true
        description: "git tag to pull, ex: v1.0.0"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: refs/tags/${{ inputs.git-tag }}

# just a POC.  If built out, this would build and push an image to artifactory w/ version tag
