name: Deploy

on: 
  release:
    types: [released]

jobs:
  deploy_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ GITHUB_REF }}

# This is just a POC.  At this point we would build, push and deploy
