name: Deploy

on: 
  release:
    types: [published]

jobs:
  deploy_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

# This is just a POC.  At this point we would build, push and deploy.
