# triggered on new release being published
# checkout the latest tag
# pull that image from artifactory
# pushes the image to staging ecr
# creates new staging task definition and deploys it
# manual approve deploy to prod
# checks out the image from artifactory
# pushes the image to prod ecr
# creates new prod task definition and deploys it
