name: Re-deploy past release

on:
  workflow_dispatch:
    inputs:
      git-tag:
        description: 'tag to deploy'
        type: string
        required: true

jobs:
  deploy:
    name: Deploy to Staging and Prod
    uses: ./.github/workflows/callable-deploy-prod.yml
    with:
      git-tag: ${{ inputs.git-tag }}
