name: Release

# change this to run on pushes to main
# manual approval after dry run?
# create release, get version
# build image, bake version into image as env file, tag image with version
# push to artifactory


on:
  push:
    branches:
      - main

jobs:
  dry-run:
    name: Release Dry Run
    runs-on: ubuntu-latest
    if: $${{ github.ref_type == 'branch' && github.ref_name == 'main'}}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Install tooling dependencies
        run: pnpm install

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm run release