name: Validate PR Title

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^\[(([A-Z0-9]{2,}-[0-9]+)|(NO-TICKET))\]\s(\[CHERRY-PICK\]\s)?[A-Z].{3,}$'
          min_length: 10
          max_length: 80
